### ISSUE TITLE
Create Data Base 

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#10]
Create Data Base using Xammp

**Comment by Josh1421** [comment]
![image](https://user-images.githubusercontent.com/75637363/146572912-ce83a2ce-48c9-46f2-a873-2108661cb174.png)

**Comment by Josh1421** [comment]
![image](https://user-images.githubusercontent.com/75637363/146573183-f6b1d014-aabf-48ec-a596-61cd2c8bcf1c.png)
