### ISSUE TITLE
Practicing CRUD

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#13]

**Comment by mhicaella** [comment]
![270636148_264221305781373_8733124636486464546_n](https://user-images.githubusercontent.com/94753054/149746985-a8964171-3c49-4ac9-b794-08f7233b1fb2.png)
![271045429_1962627413918829_6385647424969477998_n](https://user-images.githubusercontent.com/94753054/149746994-5e71a285-7314-4d99-b1e5-5218d6acaf18.png)

**Comment by georeeen** [comment]
![received_673822747299478.jpeg](https://user-images.githubusercontent.com/94753197/149756969-18282be4-6922-4f38-a863-02c8d8371cc9.jpeg)
