### ISSUE TITLE
Auto-Generated PDF file for Barangay Clearance & Barangay Business Permit

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#28]

**Comment by georeeen** [comment]
![Barangay Business Permit.jpeg](https://user-images.githubusercontent.com/94753197/153419107-7e968b11-106a-4cfc-b204-d562c83b7251.jpeg)

**Comment by georeeen** [comment]
![Barangay Clearance.jpeg](https://user-images.githubusercontent.com/94753197/153419170-ef2638a8-96d3-47eb-814b-83ee0200806d.jpeg)
