### ISSUE TITLE
Fix UI for features

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#29]

**Comment by Josh1421** [comment]
![261746890_785475139512363_258876549302239154_n](https://user-images.githubusercontent.com/75637363/153417031-d4a3b5d2-7b82-4bad-8fc5-721acee5a98f.png)
![260044357_934049530814402_7262623461172402219_n](https://user-images.githubusercontent.com/75637363/153417041-5aa20a39-0464-4f82-a310-ac01d15ef8b9.png)
![272711768_312096050936505_1606874422094638380_n](https://user-images.githubusercontent.com/75637363/153417045-a1539739-ad57-4088-b198-ca4351caa6d5.png)
![248323500_488695016046436_2759360615465916480_n](https://user-images.githubusercontent.com/75637363/153417057-13ac09e0-ee11-47fc-b9b3-a729bc2d655c.png)
