### ISSUE TITLE
Inbox feature

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#30]

**Comment by mhicaella** [comment]
![Uploading 262195098_1805807552962108_5523248969361632898_n.png…]()

**Comment by mhicaella** [comment]
![262195098_1805807552962108_5523248969361632898_n](https://user-images.githubusercontent.com/94753054/153437989-e4a62d0b-d66f-4c20-8008-0a5868606721.png)
