### ISSUE TITLE
Updated Wireframe

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#34]

**Comment by rymrc** [comment]
![CONTACT](https://user-images.githubusercontent.com/94752951/152827714-dcd5f026-9526-47f4-9462-cdeb110e07f7.jpg)
![HOMEPAGE](https://user-images.githubusercontent.com/94752951/152827720-a8e51ccf-8270-4531-90ec-5d45962ac234.png)
![Login](https://user-images.githubusercontent.com/94752951/152827722-ebf3fd1f-757e-498b-8874-f31bb92328ab.jpg)
![WELCOME](https://user-images.githubusercontent.com/94752951/152827724-b4ed8c81-2325-4afc-9d0d-c9e2c3609e8c.jpg)
![BBA](https://user-images.githubusercontent.com/94752951/152827726-811bb5c0-f4ae-489f-b6f4-9e32feda707c.jpg)
![BBR](https://user-images.githubusercontent.com/94752951/152827728-29720db5-6db8-42b3-a0f5-e03cc1024a13.jpg)
![BCA](https://user-images.githubusercontent.com/94752951/152827731-effd6196-56f3-48fd-ba5f-ec3d540981f8.jpg)
![COMPLAINT](https://user-images.githubusercontent.com/94752951/152827735-6de5e5b6-67bd-4dd3-8f49-497ba7b468cc.png)

**Comment by jaeam17** [comment]
![Barangay System Admin Wireframe drawio](https://user-images.githubusercontent.com/73686898/153237361-ccc59754-4be6-45bd-a4c7-4318e88470c1.png)
![Barangay System Admin WIreframe2 drawio](https://user-images.githubusercontent.com/73686898/153237438-2b395014-51c3-42ca-bfb5-016b3e455371.png)
