### ISSUE TITLE
WireFrame

### ISSUE THREAD

**Issue by jaeam17** [jaeam17/Team01--BSIS3AB#9]
Creating the website's Wire frame

**Comment by rymrc** [comment]
![MainPage](https://user-images.githubusercontent.com/94752951/146492249-d50588f1-2854-4f4f-a49b-3e9906e93536.jpg)

**Comment by rymrc** [comment]
![Login](https://user-images.githubusercontent.com/94752951/146492285-7ff71924-5d4b-4a2e-92de-7fa27984a4ea.jpg)

**Comment by rymrc** [comment]
![Register](https://user-images.githubusercontent.com/94752951/146492297-435a4229-69c1-4f18-9a4f-560079cac1f2.jpg)

**Comment by rymrc** [comment]
![ComplaintForm](https://user-images.githubusercontent.com/94752951/146492320-86d5e5f9-fa68-4dea-be07-bbcb7cf600cb.jpg)

**Comment by rymrc** [comment]
![Permit](https://user-images.githubusercontent.com/94752951/146492336-5feeff38-ba72-4483-bada-3c34be81d885.jpg)

**Comment by rymrc** [comment]
![Clearance](https://user-images.githubusercontent.com/94752951/146492350-0ab96687-12d0-4b28-8885-caedf4dc6b8d.jpg)

**Comment by rymrc** [comment]
![Rent](https://user-images.githubusercontent.com/94752951/146492361-eabc01fa-e253-4b29-8956-aa3465906109.jpg)
